### ISSUE TITLE
Days before today needs to be numeric under conditions in the List Layout

### ISSUE THREAD

**Issue by shankarshegde** [SubscribeIT/ngDesk#357]
**Owner:** @sharath-satish 

**Task Type:** 
- [ ] New 
- [ x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

As a System Admin user, ngDesk should allow me to type in/select the number of days under (all date relevant) conditions while configuring a List Layout. 
Currently, it is giving dates to select as shown in the below screenshot which is wrong.

![image](https://user-images.githubusercontent.com/89568062/152334936-37bb30e4-a752-4773-987f-72c83c897d54.png)

For your reference, below is the screenshot from **Reports** under ngDesk where it is allowing me to select/type in the number of days after choosing **Days before today** under the filter. The same way, it should give me an option to type in/select the number of days under conditions while configuring a List Layout. 

![image](https://user-images.githubusercontent.com/89568062/152335639-88e231e4-1dab-4250-9bed-dad3df291d89.png)

**List of Steps:**

**Test Criteria:**

**Comment by unagireddy** [comment]
Issue gottested based on 
posted a company open the tickets in sidebar module. create a active ticket in list layout with active ticktes of system admin.checked by creating the ticket by adding the values manually in day before toda in meet all conditons.
only numeric data can add and edit but not alpha
no error oberved while adding or editing and saving
/time 3 hours

**Comment by abs-ravi** [comment]
**Completed:-**

- added Days before today in condition for all tickets layouts
- not able to see owl date picker
- able to select no of days instead of owl date picker
- able to filter tickets on condition ( Days before today operator)

**Screenshots**

![Screenshot from 2022-02-08 09-23-48](https://user-images.githubusercontent.com/89505098/152915644-fa81a811-31e2-4fbb-a49d-0e83ef3cdf12.png)
![Screenshot from 2022-02-08 09-24-00](https://user-images.githubusercontent.com/89505098/152915651-14940037-05db-45bf-b5a1-a5252c2c86c1.png)
![Screenshot from 2022-02-08 09-24-12](https://user-images.githubusercontent.com/89505098/152915653-2567b8dd-f5c8-4529-a610-d0d0b0d09bea.png)
