### ISSUE TITLE
Spacing Issue

### ISSUE THREAD

**Issue by AyushAllBlue** [SubscribeIT/ngDesk#43]
**Owner:** @ssatish 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** Ng Desk Ui

**Components/Services Affected (Ex. Login Component, POST Data API):**Expense Module

**General Description/Overview:**
![27](https://user-images.githubusercontent.com/89504119/130953306-e1e0e10a-784c-40f0-9b85-95cd65d8dfad.png)

As a TYPE_OF_USER_OR_ROLE, I want SOME_GOAL so that SOME_REASON_OR_BENEFIT.

**List of Steps:**
- [ ]As a task, space has to be added between Expense Reports and the right side of the sidebar
-  

**Test Criteria:**
- [x] As a task ,check if space has to be added between Expense Reports and the right side of the sidebar

**Comment by AyushAllBlue** [comment]
Issue is fixed already

**Comment by AyushAllBlue** [comment]
![Screenshot from 2021-08-30 10-17-11](https://user-images.githubusercontent.com/89504119/131286613-55644648-2fec-4540-b808-b7160a30f05e.png)

**Comment by sdthengil** [comment]
The issue is not replicating.Performed below steps while testing.

1.posted a new company with "Expenses" plugin
2.Go to sidebar and clicked on Expenses and expand it .
3.Observed the space between  Expense Reports and the right side of the sidebar and the spacing was proper
4.Observed no error.

The issue is fixed.

/spend 30m

**Comment by karthikbalu1** [comment]
Since the issue is already fixed and not able to replicate issue, the issue will be closed.
