### ISSUE TITLE
Modules - Autopopulating field values based on another field

### ISSUE THREAD

**Issue by CHINMAYJAIN03** [SubscribeIT/ngDesk#63]
Ex: with expenses, if i had a field category (picklist) with selected option that relates to "personal expense", another field called personal expense would be set to true.

**Comment by AyushAllBlue** [comment]
- I think this issue is a feature of inheritance mapping, i checked the issue in git lab.
- Created by nithin long back in git lab.
- Inheritance mapping feature is already added.
- Above line, is just an example about how the feature is going to work.
- So, feature is already added and it is not a bug.

**Comment by karthikbalu1** [comment]
Since this issue is related to enhancement, and this feature had been implemented already the issue will be closed.
